# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sasaovch/Development/ITMO/lab_1_llp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sasaovch/Development/ITMO/lab_1_llp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sasaovch/Development/ITMO/lab_1_llp/CMakeFiles /Users/sasaovch/Development/ITMO/lab_1_llp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sasaovch/Development/ITMO/lab_1_llp/CMakeFiles 0
	rm -f data
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llp

# Build rule for target.
llp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llp
.PHONY : llp

# fast build rule for target.
llp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/build
.PHONY : llp/fast

#=============================================================================
# Target rules for targets named llp_lib

# Build rule for target.
llp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llp_lib
.PHONY : llp_lib

# fast build rule for target.
llp_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/build
.PHONY : llp_lib/fast

src/data/common.o: src/data/common.c.o
.PHONY : src/data/common.o

# target to build an object file
src/data/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/common.c.o
.PHONY : src/data/common.c.o

src/data/common.i: src/data/common.c.i
.PHONY : src/data/common.i

# target to preprocess a source file
src/data/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/common.c.i
.PHONY : src/data/common.c.i

src/data/common.s: src/data/common.c.s
.PHONY : src/data/common.s

# target to generate assembly for a file
src/data/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/common.c.s
.PHONY : src/data/common.c.s

src/data/crud_methods.o: src/data/crud_methods.c.o
.PHONY : src/data/crud_methods.o

# target to build an object file
src/data/crud_methods.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/crud_methods.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/crud_methods.c.o
.PHONY : src/data/crud_methods.c.o

src/data/crud_methods.i: src/data/crud_methods.c.i
.PHONY : src/data/crud_methods.i

# target to preprocess a source file
src/data/crud_methods.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/crud_methods.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/crud_methods.c.i
.PHONY : src/data/crud_methods.c.i

src/data/crud_methods.s: src/data/crud_methods.c.s
.PHONY : src/data/crud_methods.s

# target to generate assembly for a file
src/data/crud_methods.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/crud_methods.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/crud_methods.c.s
.PHONY : src/data/crud_methods.c.s

src/data/node.o: src/data/node.c.o
.PHONY : src/data/node.o

# target to build an object file
src/data/node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/node.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/node.c.o
.PHONY : src/data/node.c.o

src/data/node.i: src/data/node.c.i
.PHONY : src/data/node.i

# target to preprocess a source file
src/data/node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/node.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/node.c.i
.PHONY : src/data/node.c.i

src/data/node.s: src/data/node.c.s
.PHONY : src/data/node.s

# target to generate assembly for a file
src/data/node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/node.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/node.c.s
.PHONY : src/data/node.c.s

src/data/page.o: src/data/page.c.o
.PHONY : src/data/page.o

# target to build an object file
src/data/page.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/page.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/page.c.o
.PHONY : src/data/page.c.o

src/data/page.i: src/data/page.c.i
.PHONY : src/data/page.i

# target to preprocess a source file
src/data/page.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/page.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/page.c.i
.PHONY : src/data/page.c.i

src/data/page.s: src/data/page.c.s
.PHONY : src/data/page.s

# target to generate assembly for a file
src/data/page.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/page.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/page.c.s
.PHONY : src/data/page.c.s

src/data/property.o: src/data/property.c.o
.PHONY : src/data/property.o

# target to build an object file
src/data/property.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/property.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/property.c.o
.PHONY : src/data/property.c.o

src/data/property.i: src/data/property.c.i
.PHONY : src/data/property.i

# target to preprocess a source file
src/data/property.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/property.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/property.c.i
.PHONY : src/data/property.c.i

src/data/property.s: src/data/property.c.s
.PHONY : src/data/property.s

# target to generate assembly for a file
src/data/property.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/property.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/property.c.s
.PHONY : src/data/property.c.s

src/data/relationship.o: src/data/relationship.c.o
.PHONY : src/data/relationship.o

# target to build an object file
src/data/relationship.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/relationship.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/relationship.c.o
.PHONY : src/data/relationship.c.o

src/data/relationship.i: src/data/relationship.c.i
.PHONY : src/data/relationship.i

# target to preprocess a source file
src/data/relationship.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/relationship.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/relationship.c.i
.PHONY : src/data/relationship.c.i

src/data/relationship.s: src/data/relationship.c.s
.PHONY : src/data/relationship.s

# target to generate assembly for a file
src/data/relationship.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/relationship.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/relationship.c.s
.PHONY : src/data/relationship.c.s

src/data/specific.o: src/data/specific.c.o
.PHONY : src/data/specific.o

# target to build an object file
src/data/specific.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/specific.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/specific.c.o
.PHONY : src/data/specific.c.o

src/data/specific.i: src/data/specific.c.i
.PHONY : src/data/specific.i

# target to preprocess a source file
src/data/specific.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/specific.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/specific.c.i
.PHONY : src/data/specific.c.i

src/data/specific.s: src/data/specific.c.s
.PHONY : src/data/specific.s

# target to generate assembly for a file
src/data/specific.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/specific.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/specific.c.s
.PHONY : src/data/specific.c.s

src/data/type.o: src/data/type.c.o
.PHONY : src/data/type.o

# target to build an object file
src/data/type.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/type.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/type.c.o
.PHONY : src/data/type.c.o

src/data/type.i: src/data/type.c.i
.PHONY : src/data/type.i

# target to preprocess a source file
src/data/type.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/type.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/type.c.i
.PHONY : src/data/type.c.i

src/data/type.s: src/data/type.c.s
.PHONY : src/data/type.s

# target to generate assembly for a file
src/data/type.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/data/type.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/data/type.c.s
.PHONY : src/data/type.c.s

src/io/io.o: src/io/io.c.o
.PHONY : src/io/io.o

# target to build an object file
src/io/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/io/io.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/io/io.c.o
.PHONY : src/io/io.c.o

src/io/io.i: src/io/io.c.i
.PHONY : src/io/io.i

# target to preprocess a source file
src/io/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/io/io.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/io/io.c.i
.PHONY : src/io/io.c.i

src/io/io.s: src/io/io.c.s
.PHONY : src/io/io.s

# target to generate assembly for a file
src/io/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/io/io.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/io/io.c.s
.PHONY : src/io/io.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils/page_utils.o: src/utils/page_utils.c.o
.PHONY : src/utils/page_utils.o

# target to build an object file
src/utils/page_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/page_utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/page_utils.c.o
.PHONY : src/utils/page_utils.c.o

src/utils/page_utils.i: src/utils/page_utils.c.i
.PHONY : src/utils/page_utils.i

# target to preprocess a source file
src/utils/page_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/page_utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/page_utils.c.i
.PHONY : src/utils/page_utils.c.i

src/utils/page_utils.s: src/utils/page_utils.c.s
.PHONY : src/utils/page_utils.s

# target to generate assembly for a file
src/utils/page_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/page_utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/page_utils.c.s
.PHONY : src/utils/page_utils.c.s

src/utils/test_data.o: src/utils/test_data.c.o
.PHONY : src/utils/test_data.o

# target to build an object file
src/utils/test_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/test_data.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/test_data.c.o
.PHONY : src/utils/test_data.c.o

src/utils/test_data.i: src/utils/test_data.c.i
.PHONY : src/utils/test_data.i

# target to preprocess a source file
src/utils/test_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/test_data.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/test_data.c.i
.PHONY : src/utils/test_data.c.i

src/utils/test_data.s: src/utils/test_data.c.s
.PHONY : src/utils/test_data.s

# target to generate assembly for a file
src/utils/test_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp.dir/build.make CMakeFiles/llp.dir/src/utils/test_data.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llp_lib.dir/build.make CMakeFiles/llp_lib.dir/src/utils/test_data.c.s
.PHONY : src/utils/test_data.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... llp"
	@echo "... llp_lib"
	@echo "... src/data/common.o"
	@echo "... src/data/common.i"
	@echo "... src/data/common.s"
	@echo "... src/data/crud_methods.o"
	@echo "... src/data/crud_methods.i"
	@echo "... src/data/crud_methods.s"
	@echo "... src/data/node.o"
	@echo "... src/data/node.i"
	@echo "... src/data/node.s"
	@echo "... src/data/page.o"
	@echo "... src/data/page.i"
	@echo "... src/data/page.s"
	@echo "... src/data/property.o"
	@echo "... src/data/property.i"
	@echo "... src/data/property.s"
	@echo "... src/data/relationship.o"
	@echo "... src/data/relationship.i"
	@echo "... src/data/relationship.s"
	@echo "... src/data/specific.o"
	@echo "... src/data/specific.i"
	@echo "... src/data/specific.s"
	@echo "... src/data/type.o"
	@echo "... src/data/type.i"
	@echo "... src/data/type.s"
	@echo "... src/io/io.o"
	@echo "... src/io/io.i"
	@echo "... src/io/io.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/page_utils.o"
	@echo "... src/utils/page_utils.i"
	@echo "... src/utils/page_utils.s"
	@echo "... src/utils/test_data.o"
	@echo "... src/utils/test_data.i"
	@echo "... src/utils/test_data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

